version: '3'
services:
  backend:
    image: "088582823373.dkr.ecr.us-east-1.amazonaws.com/ttt-backend:latest"
    container_name: "ttt-backend"
    depends_on:
      - postgres

  frontend:
    image: "088582823373.dkr.ecr.us-east-1.amazonaws.com/ttt-frontend:latest"
    container_name: "ttt-frontend"
    ports:
      - "80:80"
    depends_on:
      - backend