version: '3'
services:
  postgres:
    image: "postgres:14.5"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  backend:
    build:
      context: ./backend/
    ports:
      - "8081:3001"
    environment:
      CORS_ORIGIN: "http://localhost:8080"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: "test"
      DATABASE_PASSWORD: "test"
      DATABASE_NAME: "test"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend/
    ports:
      - "8080:80"
    environment:
      API_URL: "http://localhost:8081"
    depends_on:
      - backend