version: '3'
services:
  postgres:
    image: "postgres:14.5"
    container_name: "ttt-db"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  backend:
    build:
      context: ./backend/
    image: "devarcana/ttt-backend:latest"
    container_name: "ttt-backend"
    ports:
      - "3001:3001"
    environment:
      CORS_ORIGIN: "http://pwr-z-loadb-r8q6b2ya0xv1-1416532704.us-east-1.elb.amazonaws.com/"
      DATABASE_HOST: "postgres"
      DATABASE_PORT: "5432"
      DATABASE_USERNAME: "test"
      DATABASE_PASSWORD: "test"
      DATABASE_NAME: "test"
    depends_on:
      - postgres

  frontend:
    build:
      context: ./frontend/
    image: "devarcana/ttt-frontend:latest"
    container_name: "ttt-frontend"
    ports:
      - "80:80"
    environment:
      API_URL: "http://pwr-z-loadb-r8q6b2ya0xv1-1416532704.us-east-1.elb.amazonaws.com:3001"
    depends_on:
      - backend